name: Lint Annotations
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "13"
      - name: Check Dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-cache-${{ github.job }}
          restore-keys: yarn-cache-
      - name: Install Dependencies
        run: yarn install
      - name: Lint Packages
        uses: bradennapier/eslint-plus-action@v3
