name: Seperate CI
on: pull_request
env:
  TZ: "America/Los_Angeles"
jobs:
  ci-lint:
    name: CI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            ~/example-projects/next/node_modules
            ~/example-projects/next-scheduler/node_modules
            ~/example-projects/nuxt/node_modules
            ~/example-projects/vue-vuex/node_modules
            ~/example-projects/vue-typescript/node_modules
            ~/example-projects/parcel/node_modules
          key: modules-${{ hashFiles('yarn.lock')}}
          restore-keys: modules-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - run: yarn run lint
      - name: Build Project
        run: yarn run build
      - run: yarn run lintBuilt
  ci-test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            ~/example-projects/next/node_modules
            ~/example-projects/next-scheduler/node_modules
            ~/example-projects/nuxt/node_modules
            ~/example-projects/vue-vuex/node_modules
            ~/example-projects/vue-typescript/node_modules
            ~/example-projects/parcel/node_modules
          key: modules-${{ hashFiles('yarn.lock')}}
          restore-keys: modules-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Project
        run: yarn run build
      - run: yarn run test:ci
  ci-contrib:
    name: CI Contrib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            ~/example-projects/next/node_modules
            ~/example-projects/next-scheduler/node_modules
            ~/example-projects/nuxt/node_modules
            ~/example-projects/vue-vuex/node_modules
            ~/example-projects/vue-typescript/node_modules
            ~/example-projects/parcel/node_modules
          key: modules-${{ hashFiles('yarn.lock')}}
          restore-keys: modules-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Project
        run: yarn run build
      - run: yarn run contrib:run all ci
      - run: FULLCALENDAR_FORCE_REACT=1 yarn run test:ci
  ci-examples:
    name: CI Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            ~/example-projects/next/node_modules
            ~/example-projects/next-scheduler/node_modules
            ~/example-projects/nuxt/node_modules
            ~/example-projects/vue-vuex/node_modules
            ~/example-projects/vue-typescript/node_modules
            ~/example-projects/parcel/node_modules
          key: modules-${{ hashFiles('yarn.lock')}}
          restore-keys: modules-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Project
        run: yarn run build
      - run: yarn run contrib:run all build
      - run: yarn run example:run all build
